### ISSUE TITLE
TypeError: 'OpenGLRenderer' object is not callable

### ISSUE THREAD

**Issue by josangmi** [UnMolDeQuimica/manim-Chemistry#17]
Mac OS 14.7
python3.11 manim 0.18.1

##
manim examples.py Draw3DMorphine -ps --renderer=opengl   

Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/manim/scene/scen │
│ e.py:141 in __init__                                                                             │
│                                                                                                  │
│    138 │   │   │   │   renderer = OpenGLRenderer()                                               │
│    139 │   │                                                                                     │
│    140 │   │   if renderer is None:                                                              │
│ ❱  141 │   │   │   self.renderer = CairoRenderer(                                                │
│    142 │   │   │   │   camera_class=self.camera_class,                                           │
│    143 │   │   │   │   skip_animations=self.skip_animations,                                     │
│    144 │   │   │   )                                                                             │
│                                                                                                  │
│ /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/manim/renderer/c │
│ airo_renderer.py:45 in __init__                                                                  │
│                                                                                                  │
│    42 │   │   # _instance construction_.                                                         │
│    43 │   │   self._file_writer_class = file_writer_class                                        │
│    44 │   │   camera_cls = camera_class if camera_class is not None else Camera                  │
│ ❱  45 │   │   self.camera = camera_cls()                                                         │
│    46 │   │   self._original_skipping_status = skip_animations                                   │
│    47 │   │   self.skip_animations = skip_animations                                             │
│    48 │   │   self.animations_hashes = []    

TypeError: 'OpenGLRenderer' object is not callable

**Comment by UnMolDeQuimica** [comment]
Hi!

This error is related to the way the renderer is configured inside the examples. Even if the `config.renderer` parameter is inside the classes, Manim takes the last entry of the renderer to select its renderer.

Example:

```python
from manim import *

config.renderer = "cairo" # Sets cairo as renderer

class MyScene(Scene)
    def construct(self):
        self.wait()


class MyOtherScene(Scene)
    confi.renderer = "opengl" # Sets opengl for both 'MyScene' and 'MyOtherScene'
    def construct(self):
        self.wait()
```


As a result, when trying to run the examples from the `examples.py` folder, you should copy the example you want to run into another file to avoid overwritting the conifig.

**Comment by josangmi** [comment]
Thx, I fix it.
