### ISSUE TITLE
A cool function that can be added

### ISSUE THREAD

**Issue by thinktraveller** [UnMolDeQuimica/manim-Chemistry#33]
When I was making video, I found something was wrong:
![屏幕截图 2024-11-30 110050](https://github.com/user-attachments/assets/294d062d-a737-4d11-b642-25f63ac9c083)
In this picture, I want to show the  coordination bond between Ni and C=C bond, however, there is no function to get the midpoint of C=C bond, which make me difficult to get the start point of the arrow. 
By analogy, the same thing happen when I want to show the coordination bond between the Ni and N atom of pyridne.

So I think there should be a function to get the every location of atoms and bonds, which can make it easier to show the relation between molecules/:D

**Comment by UnMolDeQuimica** [comment]
Hi!! How are you doing? I just added some changes in a new branch. I will merge it to main

**Comment by UnMolDeQuimica** [comment]
Hi! I just created a PR with the changes requested in this issue. I added the following functions:

*MMoleculeObject and NamedMolecule:*
- `find_atom_position_by_index`: Given an atom index you get its position.
- `find_atoms_position_by_index`: Given a list of atoms index you get their positions.
- `find_bond_center_by_index`: Given a bond index you get its center.
- `find_bonds_center_by_index`: Given a list of bonds you get their center.
- `find_position_along_bond_axis`: Given a bond index and a position buff you get a point along the bond axis. 1 returns one end of the bond, -1 the other, 0 the center. Between -1 and 1 you get points inside the bond. For values smaller than -1 or bigger than 1 you get points outside of the bond along the axis. 
- `find_all_atoms_positions`: Returns a dictionary with the atoms index and their positions
- `find_all_bonds_centers`: Returns a dictionary with the bonds index and their centers.

*GraphMolecule*
The functions are pretty much the same. The only difference is we use `find_bond_center_by_tuple` and `find_bonds_center_by_tuple` instead of `find_bond_center_by_index` and `find_bonds_center_by_index`

I will merge the PR and create a new tag and a new release so you can use the functions. Let me know if this is what you expected!

# Simple example

```python
molecule = GraphMolecule.build_from_mol("examples/element_files/dimethylpropane.mol")
print(molecule.find_atom_position_by_index(1))
>>> array([ 0.9397, -0.7497,  0.    ])
print(molecule.find_atoms_position_by_index([1,2,3]))
>>> [array([ 0.0713, -0.0263,  0.    ]), array([-1.2754,  0.3464,  0.    ]), array([0.9674, 1.2186, 0.    ])]
print(molecule.find_bond_center_by_tuple((1, 2))
>>> array([0.51935, 0.59615, 0.     ])
```

# A more complex example:
I made a very simple (and horrible) animation on SN2 substitution using those new functions:

```python
from manim import *
from manim_chemistry import *

class SN2ExampleGraphMolecule(Scene):
    def construct(self):
        methcl = GraphMolecule.build_from_mol(mol_file="methcl.mol").shift(RIGHT)
        oh = GraphMolecule.build_from_mol(mol_file="oh.mol").shift(2*LEFT)
        oh_charge_top = Text("−", color=oh.atoms[1].get_color()).next_to(oh.atoms[1], UP, buff=0.1)
        oh_charge_side = Text("−", color=oh.atoms[1].get_color()).rotate(90*DEGREES).next_to(oh.atoms[1], RIGHT, buff=0.1)
        oh_charge_bottom = Text("−", color=oh.atoms[1].get_color()).next_to(oh.atoms[1], DOWN, buff=0.1)
        
        oh_group = VGroup(oh, oh_charge_top, oh_charge_side, oh_charge_bottom).to_edge().rotate(-40*DEGREES, about_point=oh.atoms[1].get_center())

        self.wait()
        self.play(
            FadeIn(methcl, oh_group)
        )
        self.wait()
        self.play(
            methcl.atoms[2].animate.shift(2*RIGHT),
            methcl.atoms[3].animate.shift(2*RIGHT),
            methcl.atoms[4].animate.shift(2*RIGHT),
            methcl.atoms[5].animate.shift(2*RIGHT),
            oh_group.animate.shift(4.5*RIGHT),
            run_time=3
        )
        cl_charge = Line(color=methcl.atoms[5].get_color()).rotate(90*DEGREES).scale(0.2)
        cl_charge.next_to(methcl.atoms[5], LEFT, buff=0.1)
        self.wait()
        
        # This will be used to get the buff positions between the oxygen and the carbon, it is not meant to be drawn
        o_c_arrow = Arrow(oh_charge_side.get_center(), methcl.find_atom_position_by_index(1), buff=0.2)
        # This is the arrow actually being drawn
        o_c_curved_arrow = CurvedArrow(o_c_arrow.get_start(), o_c_arrow.get_end())
        
        # I used an extra 0.2 down but you could simply get the bottom of the atom:
        # metchcl.atoms[5].get_bottom()
        bond_cl_arrow = CurvedArrow(methcl.find_bond_center_by_tuple((1, 5)), methcl.find_atom_position_by_index(5) + 0.2*DOWN)
        
        self.play(Write(o_c_curved_arrow))
        self.wait()
        self.play(Write(bond_cl_arrow))
        self.wait()
        o_c_bond = Line(
            start=oh.find_atom_position_by_index(1), 
            end=methcl.find_atom_position_by_index(1), 
            z_index=-1, # This puts the bond below the atoms
        ).set_color_by_gradient(color_gradient([
                methcl.atoms[1].get_color(),
                oh.atoms[1].get_color(),
            ], 2
            )
        )
        
        self.play(
            Unwrite(o_c_curved_arrow), 
            Unwrite(bond_cl_arrow)
        )

        cl_bond = methcl.bonds[(1, 5)]
        self.play(
            ReplacementTransform(oh_charge_side, o_c_bond),
            ReplacementTransform(cl_bond, cl_charge)
        )
        
        self.wait()
```
Result:
![SN2ExampleGraphMolecule_ManimCE_v0 17 3](https://github.com/user-attachments/assets/135984be-11c8-45a6-b54f-b2ff2aaa129b)



You can see that the transformation of the C - Cl bond is not beautiful at all. That's a manim error, not an error from manim chemistry. 

However, I think that it shows how to use the functions! Hope you like it.

**Comment by thinktraveller** [comment]
the six row of "Simple example" maybe lose a ")"
it should be corrected into "print(molecule.find_bond_center_by_tuple((1, 2)))"

**Comment by thinktraveller** [comment]
> the six row of "Simple example" maybe lose a ")" it should be corrected into "print(molecule.find_bond_center_by_tuple((1, 2)))"



> Hi! I just created a PR with the changes requested in this issue. I added the following functions:
> 
> _MMoleculeObject and NamedMolecule:_
> 
> * `find_atom_position_by_index`: Given an atom index you get its position.
> * `find_atoms_position_by_index`: Given a list of atoms index you get their positions.
> * `find_bond_center_by_index`: Given a bond index you get its center.
> * `find_bonds_center_by_index`: Given a list of bonds you get their center.
> * `find_position_along_bond_axis`: Given a bond index and a position buff you get a point along the bond axis. 1 returns one end of the bond, -1 the other, 0 the center. Between -1 and 1 you get points inside the bond. For values smaller than -1 or bigger than 1 you get points outside of the bond along the axis.
> * `find_all_atoms_positions`: Returns a dictionary with the atoms index and their positions
> * `�find_all_bonds_centers`: Returns a dictionary with the bonds index and their centers.
> 
> _GraphMolecule_ The functions are pretty much the same. The only difference is we use `find_bond_center_by_tuple` and `find_bonds_center_by_tuple` instead of `find_bond_center_by_index` and `find_bonds_center_by_index`
> 
> I will merge the PR and create a new tag and a new release so you can use the functions. Let me know if this is what you expected!
> 
> # Simple example
> ```python
> molecule = GraphMolecule.build_from_mol("examples/element_files/dimethylpropane.mol")
> print(molecule.find_atom_position_by_index(1))
> >>> array([ 0.9397, -0.7497,  0.    ])
> print(molecule.find_atoms_position_by_index([1,2,3]))
> >>> [array([ 0.0713, -0.0263,  0.    ]), array([-1.2754,  0.3464,  0.    ]), array([0.9674, 1.2186, 0.    ])]
> print(molecule.find_bond_center_by_tuple((1, 2))
> >>> array([0.51935, 0.59615, 0.     ])
> ```
> 
> # A more complex example:
> I made a very simple (and horrible) animation on SN2 substitution using those new functions:
> 
> ```python
> from manim import *
> from manim_chemistry import *
> 
> class SN2ExampleGraphMolecule(Scene):
>     def construct(self):
>         methcl = GraphMolecule.build_from_mol(mol_file="methcl.mol").shift(RIGHT)
>         oh = GraphMolecule.build_from_mol(mol_file="oh.mol").shift(2*LEFT)
>         oh_charge_top = Text("−", color=oh.atoms[1].get_color()).next_to(oh.atoms[1], UP, buff=0.1)
>         oh_charge_side = Text("−", color=oh.atoms[1].get_color()).rotate(90*DEGREES).next_to(oh.atoms[1], RIGHT, buff=0.1)
>         oh_charge_bottom = Text("−", color=oh.atoms[1].get_color()).next_to(oh.atoms[1], DOWN, buff=0.1)
>         
>         oh_group = VGroup(oh, oh_charge_top, oh_charge_side, oh_charge_bottom).to_edge().rotate(-40*DEGREES, about_point=oh.atoms[1].get_center())
> 
>         self.wait()
>         self.play(
>             FadeIn(methcl, oh_group)
>         )
>         self.wait()
>         self.play(
>             methcl.atoms[2].animate.shift(2*RIGHT),
>             methcl.atoms[3].animate.shift(2*RIGHT),
>             methcl.atoms[4].animate.shift(2*RIGHT),
>             methcl.atoms[5].animate.shift(2*RIGHT),
>             oh_group.animate.shift(4.5*RIGHT),
>             run_time=3
>         )
>         cl_charge = Line(color=methcl.atoms[5].get_color()).rotate(90*DEGREES).scale(0.2)
>         cl_charge.next_to(methcl.atoms[5], LEFT, buff=0.1)
>         self.wait()
>         
>         # This will be used to get the buff positions between the oxygen and the carbon, it is not meant to be drawn
>         o_c_arrow = Arrow(oh_charge_side.get_center(), methcl.find_atom_position_by_index(1), buff=0.2)
>         # This is the arrow actually being drawn
>         o_c_curved_arrow = CurvedArrow(o_c_arrow.get_start(), o_c_arrow.get_end())
>         
>         # I used an extra 0.2 down but you could simply get the bottom of the atom:
>         # metchcl.atoms[5].get_bottom()
>         bond_cl_arrow = CurvedArrow(methcl.find_bond_center_by_tuple((1, 5)), methcl.find_atom_position_by_index(5) + 0.2*DOWN)
>         
>         self.play(Write(o_c_curved_arrow))
>         self.wait()
>         self.play(Write(bond_cl_arrow))
>         self.wait()
>         o_c_bond = Line(
>             start=oh.find_atom_position_by_index(1), 
>             end=methcl.find_atom_position_by_index(1), 
>             z_index=-1, # This puts the bond below the atoms
>         ).set_color_by_gradient(color_gradient([
>                 methcl.atoms[1].get_color(),
>                 oh.atoms[1].get_color(),
>             ], 2
>             )
>         )
>         
>         self.play(
>             Unwrite(o_c_curved_arrow), 
>             Unwrite(bond_cl_arrow)
>         )
> 
>         cl_bond = methcl.bonds[(1, 5)]
>         self.play(
>             ReplacementTransform(oh_charge_side, o_c_bond),
>             ReplacementTransform(cl_bond, cl_charge)
>         )
>         
>         self.wait()
> ```
> 
> Result: ![SN2ExampleGraphMolecule_ManimCE_v0 17 3](https://private-user-images.githubusercontent.com/115663809/393640610-135984be-11c8-45a6-b54f-b2ff2aaa129b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5Mjg2NzIsIm5iZiI6MTczMzkyODM3MiwicGF0aCI6Ii8xMTU2NjM4MDkvMzkzNjQwNjEwLTEzNTk4NGJlLTExYzgtNDVhNi1iNTRmLWIyZmYyYWFhMTI5Yi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNDQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWViMDNjMWE0MWI3MDVhNmZiYWJmZjliMWJmMjc1NDUzM2I5OTY0NWY4ZDNlNjQ1MTkzYzQzMGIxYmUyMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X6AST20HVIUaMyCfZ_3ABtc0VjBTMYF_aq4M68h9xFs) [ ![SN2ExampleGraphMolecule_ManimCE_v0 17 3](https://private-user-images.githubusercontent.com/115663809/393640610-135984be-11c8-45a6-b54f-b2ff2aaa129b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5Mjg2NzIsIm5iZiI6MTczMzkyODM3MiwicGF0aCI6Ii8xMTU2NjM4MDkvMzkzNjQwNjEwLTEzNTk4NGJlLTExYzgtNDVhNi1iNTRmLWIyZmYyYWFhMTI5Yi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNDQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWViMDNjMWE0MWI3MDVhNmZiYWJmZjliMWJmMjc1NDUzM2I5OTY0NWY4ZDNlNjQ1MTkzYzQzMGIxYmUyMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X6AST20HVIUaMyCfZ_3ABtc0VjBTMYF_aq4M68h9xFs) ](https://private-user-images.githubusercontent.com/115663809/393640610-135984be-11c8-45a6-b54f-b2ff2aaa129b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5Mjg2NzIsIm5iZiI6MTczMzkyODM3MiwicGF0aCI6Ii8xMTU2NjM4MDkvMzkzNjQwNjEwLTEzNTk4NGJlLTExYzgtNDVhNi1iNTRmLWIyZmYyYWFhMTI5Yi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNDQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWViMDNjMWE0MWI3MDVhNmZiYWJmZjliMWJmMjc1NDUzM2I5OTY0NWY4ZDNlNjQ1MTkzYzQzMGIxYmUyMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X6AST20HVIUaMyCfZ_3ABtc0VjBTMYF_aq4M68h9xFs) [ ](https://private-user-images.githubusercontent.com/115663809/393640610-135984be-11c8-45a6-b54f-b2ff2aaa129b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5Mjg2NzIsIm5iZiI6MTczMzkyODM3MiwicGF0aCI6Ii8xMTU2NjM4MDkvMzkzNjQwNjEwLTEzNTk4NGJlLTExYzgtNDVhNi1iNTRmLWIyZmYyYWFhMTI5Yi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNDQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWViMDNjMWE0MWI3MDVhNmZiYWJmZjliMWJmMjc1NDUzM2I5OTY0NWY4ZDNlNjQ1MTkzYzQzMGIxYmUyMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X6AST20HVIUaMyCfZ_3ABtc0VjBTMYF_aq4M68h9xFs)
> 
> You can see that the transformation of the C - Cl bond is not beautiful at all. That's a manim error, not an error from manim chemistry.
> 
> However, I think that it shows how to use the functions! Hope you like it.

> the six row of "Simple example" maybe lose a ")" it should be corrected into "print(molecule.find_bond_center_by_tuple((1, 2)))"
