### ISSUE TITLE
Error with PeriodicTable

### ISSUE THREAD

**Issue by chemnerd28** [UnMolDeQuimica/manim-Chemistry#7]
When following the code for drawing the entire Periodic Table, I get the following error: 
`TypeError: Scene.__init__() got an unexpected keyword argument 'data_file'`
I tried a few different ways to write it out, but it never worked.  Is there something else I'm missing besides the provided code?

**Comment by UnMolDeQuimica** [comment]
Hi! 

I just tested it and it worked. My code is:

```python
from manim import *
from manim_chemistry import *

class Test(Scene):
    def construct(self):
        table= PeriodicTable(data_file="Elementos.csv")
        self.add(table)
``` 

In the same folder I have the file Elementos.csv that can be found in the examples assets folder.

Can you share the code you are using for this?

**Comment by chemnerd28** [comment]
I had a typo... I'll close the issue now haha sorry about that
